// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -source=service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/rusinadaria/geo-notification-system/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIncident is a mock of Incident interface.
type MockIncident struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentMockRecorder
	isgomock struct{}
}

// MockIncidentMockRecorder is the mock recorder for MockIncident.
type MockIncidentMockRecorder struct {
	mock *MockIncident
}

// NewMockIncident creates a new mock instance.
func NewMockIncident(ctrl *gomock.Controller) *MockIncident {
	mock := &MockIncident{ctrl: ctrl}
	mock.recorder = &MockIncidentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncident) EXPECT() *MockIncidentMockRecorder {
	return m.recorder
}

// CheckLocation mocks base method.
func (m *MockIncident) CheckLocation(ctx context.Context, checkReq models.LocationCheckRequest) (models.LocationCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocation", ctx, checkReq)
	ret0, _ := ret[0].(models.LocationCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocation indicates an expected call of CheckLocation.
func (mr *MockIncidentMockRecorder) CheckLocation(ctx, checkReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocation", reflect.TypeOf((*MockIncident)(nil).CheckLocation), ctx, checkReq)
}

// CreateIncident mocks base method.
func (m *MockIncident) CreateIncident(incidentData models.IncidentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIncident", incidentData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIncident indicates an expected call of CreateIncident.
func (mr *MockIncidentMockRecorder) CreateIncident(incidentData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIncident", reflect.TypeOf((*MockIncident)(nil).CreateIncident), incidentData)
}

// DeleteIncident mocks base method.
func (m *MockIncident) DeleteIncident(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIncident", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIncident indicates an expected call of DeleteIncident.
func (mr *MockIncidentMockRecorder) DeleteIncident(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIncident", reflect.TypeOf((*MockIncident)(nil).DeleteIncident), id)
}

// GetAllIncidents mocks base method.
func (m *MockIncident) GetAllIncidents(limit, offset int) ([]models.IncidentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIncidents", limit, offset)
	ret0, _ := ret[0].([]models.IncidentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIncidents indicates an expected call of GetAllIncidents.
func (mr *MockIncidentMockRecorder) GetAllIncidents(limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIncidents", reflect.TypeOf((*MockIncident)(nil).GetAllIncidents), limit, offset)
}

// GetIncidentById mocks base method.
func (m *MockIncident) GetIncidentById(id int) (models.IncidentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentById", id)
	ret0, _ := ret[0].(models.IncidentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentById indicates an expected call of GetIncidentById.
func (mr *MockIncidentMockRecorder) GetIncidentById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentById", reflect.TypeOf((*MockIncident)(nil).GetIncidentById), id)
}

// GetIncidentStats mocks base method.
func (m *MockIncident) GetIncidentStats(ctx context.Context) (models.IncidentStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentStats", ctx)
	ret0, _ := ret[0].(models.IncidentStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentStats indicates an expected call of GetIncidentStats.
func (mr *MockIncidentMockRecorder) GetIncidentStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentStats", reflect.TypeOf((*MockIncident)(nil).GetIncidentStats), ctx)
}

// UpdateIncident mocks base method.
func (m *MockIncident) UpdateIncident(id int, req models.IncidentRequest) (models.IncidentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncident", id, req)
	ret0, _ := ret[0].(models.IncidentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIncident indicates an expected call of UpdateIncident.
func (mr *MockIncidentMockRecorder) UpdateIncident(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncident", reflect.TypeOf((*MockIncident)(nil).UpdateIncident), id, req)
}

// MockHealthService is a mock of HealthService interface.
type MockHealthService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceMockRecorder
	isgomock struct{}
}

// MockHealthServiceMockRecorder is the mock recorder for MockHealthService.
type MockHealthServiceMockRecorder struct {
	mock *MockHealthService
}

// NewMockHealthService creates a new mock instance.
func NewMockHealthService(ctrl *gomock.Controller) *MockHealthService {
	mock := &MockHealthService{ctrl: ctrl}
	mock.recorder = &MockHealthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthService) EXPECT() *MockHealthServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthService) Check(ctx context.Context) models.HealthResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(models.HealthResponse)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthServiceMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthService)(nil).Check), ctx)
}

// MockWebhookQueue is a mock of WebhookQueue interface.
type MockWebhookQueue struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookQueueMockRecorder
	isgomock struct{}
}

// MockWebhookQueueMockRecorder is the mock recorder for MockWebhookQueue.
type MockWebhookQueueMockRecorder struct {
	mock *MockWebhookQueue
}

// NewMockWebhookQueue creates a new mock instance.
func NewMockWebhookQueue(ctrl *gomock.Controller) *MockWebhookQueue {
	mock := &MockWebhookQueue{ctrl: ctrl}
	mock.recorder = &MockWebhookQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookQueue) EXPECT() *MockWebhookQueueMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockWebhookQueue) Enqueue(ctx context.Context, job models.WebhookPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockWebhookQueueMockRecorder) Enqueue(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockWebhookQueue)(nil).Enqueue), ctx, job)
}
